#!/bin/bash

# Postavi hrvatsku tipkovnicu
setxkbmap hr

# Postavi pozadinu (sliku moraš imati u ~/Pictures)
feh --bg-scale ~/Pictures/wallpaper.jpg &

# Pokreni tray aplikacije
nm-applet &
volumeicon &

# Pokreni i3 window manager
exec i3
