#!/bin/bash

# Postavi pozadinu (ako želiš odmah kod startx)
feh --bg-scale ~/Slike/pozadina.jpg &

# Pokreni tray aplikacije (nije nužno jer ih već imaš u i3/config, ali možeš)
nm-applet &
volumeicon &

# Pokreni i3
exec i3
